/**
 * Button.tsx — Generated by Concorde
 * Source: http://localhost:3420/preview/components/pase1
 * Generated: 2026-05-25
 *
 * Variants: primary (pvbtn) · secondary (psec) · ghost (pghost)
 * Sizes:    md (48px) · sm (40px + icon slot)
 * States:   default · hover · active/pressed · disabled · focus-visible
 */

"use client";

import type { JSX, ReactNode } from "react";

// ---------------------------------------------------------------------------
// TYPES
// ---------------------------------------------------------------------------

type ButtonVariant = "primary" | "secondary" | "ghost";
type ButtonSize = "md" | "sm";
type ButtonAuthState = "guest" | "logged-in";

export interface ButtonProps {
  /** Visual style. Default: "primary" */
  variant?: ButtonVariant;
  /** Size. Default: "md" */
  size?: ButtonSize;
  /** sm only — icon rendered inside the pill slot */
  icon?: ReactNode;
  /** sm only — changes icon bg + username label weight */
  authState?: ButtonAuthState;
  children: ReactNode;
  disabled?: boolean;
  onClick?: () => void;
  type?: "button" | "submit" | "reset";
  "aria-label"?: string;
}

// ---------------------------------------------------------------------------
// STYLES — self-contained, no external CSS required
// ---------------------------------------------------------------------------

const BUTTON_STYLES = `
/* ── Shared shimmer overlay ─────────────────────────────────────────────── */
.ccb-pvbtn::before,
.ccb-psec::before,
.ccb-pghost::before,
.ccb-pvbtn-sm::before,
.ccb-pvbtn-auth::before {
  content: "";
  position: absolute;
  inset: 0;
  border-radius: 9999px;
  pointer-events: none;
  z-index: 1;
}

/* ── Shared glow layer ───────────────────────────────────────────────────── */
.ccb-pvbtn::after,
.ccb-psec::after,
.ccb-pvbtn-sm::after,
.ccb-pvbtn-auth::after {
  content: "";
  position: absolute;
  inset: -4px;
  border-radius: 9999px;
  filter: blur(14px);
  opacity: 0;
  z-index: -1;
  transition: opacity 0.3s, filter 0.3s;
}

.ccb-pghost::after {
  content: "";
  position: absolute;
  inset: -4px;
  border-radius: 9999px;
  background: rgba(255, 255, 255, 0.6);
  filter: blur(14px);
  opacity: 0;
  z-index: -1;
  transition: opacity 0.3s, filter 0.3s;
}

/* ══════════════════════════════════════════════════════════════════════════
   PRIMARY — .ccb-pvbtn
   Orange → Purple gradient, animated via CSS custom properties
   ══════════════════════════════════════════════════════════════════════════ */
.ccb-pvbtn {
  --vbtn-angle: 135deg;
  --vbtn-stop-a: var(--vmc-color-orange-600, #ED8936);
  --vbtn-stop-b: var(--vmc-color-vault-500, #8460E5);

  display: inline-flex;
  align-items: center;
  justify-content: center;
  height: 48px;
  padding: 0 56px;
  border-radius: 9999px;
  border: 2.5px solid transparent;
  cursor: pointer;
  position: relative;
  overflow: hidden;

  font-family: var(--vmc-font-display, "Plus Jakarta Sans", sans-serif);
  font-size: 15px;
  font-weight: 600;
  color: var(--vmc-color-base-white, #fff);
  text-shadow: rgba(0, 0, 0, 0.2) 0px 1px 2px;

  background-image:
    linear-gradient(var(--vbtn-angle), var(--vbtn-stop-a) 0%, var(--vbtn-stop-a) 40%, var(--vbtn-stop-b) 100%),
    linear-gradient(135deg, #fff 0%, #fbc47d 25%, #ae8eff 75%, #fff 100%);
  background-origin: border-box;
  background-clip: padding-box, border-box;

  box-shadow:
    rgba(255, 255, 255, 0.28) 0px 1px 0px 0px inset,
    rgba(237, 137, 54, 0.3) 0px 2px 6px 0px;

  transition:
    --vbtn-angle 0.4s cubic-bezier(0.25, 0.8, 0.25, 1),
    --vbtn-stop-a 0.35s,
    --vbtn-stop-b 0.35s,
    transform 0.2s cubic-bezier(0.25, 0.8, 0.25, 1),
    box-shadow 0.25s;
}

.ccb-pvbtn::before {
  background: linear-gradient(rgba(255, 255, 255, 0.17) 0%, transparent 55%);
}

.ccb-pvbtn::after {
  background: linear-gradient(135deg, var(--vmc-color-orange-600, #ED8936), var(--vmc-color-vault-500, #8460E5));
}

.ccb-pvbtn:hover {
  --vbtn-angle: 220deg;
  --vbtn-stop-a: var(--vmc-color-orange-400, #FBC47D);
  --vbtn-stop-b: var(--vmc-color-vault-400, #AE8EFF);
  transform: translateY(-2px) scale(1.02);
  box-shadow:
    rgba(255, 255, 255, 0.22) 0px 1px 0px inset,
    rgba(132, 96, 229, 0.35) 0px 8px 24px,
    rgba(237, 137, 54, 0.4) 0px 4px 10px;
}
.ccb-pvbtn:hover::after { opacity: 0.45; filter: blur(18px); }

.ccb-pvbtn:active {
  --vbtn-angle: 135deg;
  --vbtn-stop-a: var(--vmc-color-orange-700, #D46E20);
  --vbtn-stop-b: var(--vmc-color-vault-600, #5A35C2);
  transform: scale(0.97) translateY(1px);
  box-shadow:
    rgba(0, 0, 0, 0.22) 0px 2px 5px inset,
    rgba(0, 0, 0, 0.12) 0px 1px 3px;
}
.ccb-pvbtn:active::after { opacity: 0; }

.ccb-pvbtn:focus-visible {
  outline: 2px solid var(--vmc-color-vault-400, #AE8EFF);
  outline-offset: 3px;
}

.ccb-pvbtn:disabled {
  background-image: none;
  background-color: var(--vmc-color-background-disabled, #E1E3E2);
  color: var(--vmc-color-neutral-700, #99A1AF);
  text-shadow: none;
  box-shadow: none;
  cursor: not-allowed;
  transform: none;
  border-color: transparent;
}
.ccb-pvbtn:disabled::after { display: none; }

/* ══════════════════════════════════════════════════════════════════════════
   SECONDARY — .ccb-psec
   Purple → Deep Purple gradient
   ══════════════════════════════════════════════════════════════════════════ */
.ccb-psec {
  --vsec-angle: 160deg;
  --vsec-stop-a: var(--vmc-color-vault-500, #8460E5);
  --vsec-stop-b: var(--vmc-color-vault-700, #3B178A);

  display: inline-flex;
  align-items: center;
  justify-content: center;
  height: 48px;
  padding: 0 56px;
  border-radius: 9999px;
  border: 2.5px solid transparent;
  cursor: pointer;
  position: relative;
  overflow: hidden;

  font-family: var(--vmc-font-display, "Plus Jakarta Sans", sans-serif);
  font-size: 15px;
  font-weight: 600;
  color: var(--vmc-color-base-white, #fff);
  text-shadow: rgba(0, 0, 0, 0.2) 0px 1px 2px;

  background-image:
    linear-gradient(var(--vsec-angle), var(--vsec-stop-a) 0%, var(--vsec-stop-b) 100%),
    linear-gradient(135deg, #cfbaff 0%, #cfbaff 40%, #7b52e8 100%);
  background-origin: border-box;
  background-clip: padding-box, border-box;

  box-shadow:
    rgba(255, 255, 255, 0.22) 0px 1px 0px 0px inset,
    rgba(132, 96, 229, 0.3) 0px 2px 6px 0px;

  transition:
    --vsec-angle 0.4s cubic-bezier(0.25, 0.8, 0.25, 1),
    --vsec-stop-a 0.35s,
    --vsec-stop-b 0.35s,
    transform 0.2s cubic-bezier(0.25, 0.8, 0.25, 1),
    box-shadow 0.25s;
}

.ccb-psec::before {
  background: linear-gradient(rgba(255, 255, 255, 0.16) 0%, transparent 55%);
}

.ccb-psec::after {
  background: linear-gradient(135deg, var(--vmc-color-vault-400, #AE8EFF), var(--vmc-color-vault-600, #5A35C2));
}

.ccb-psec:hover {
  --vsec-angle: 220deg;
  --vsec-stop-a: var(--vmc-color-vault-400, #AE8EFF);
  --vsec-stop-b: var(--vmc-color-vault-600, #5A35C2);
  transform: translateY(-2px) scale(1.02);
  box-shadow:
    rgba(255, 255, 255, 0.2) 0px 1px 0px inset,
    rgba(132, 96, 229, 0.4) 0px 8px 24px,
    rgba(132, 96, 229, 0.25) 0px 4px 10px;
}
.ccb-psec:hover::after { opacity: 0.45; filter: blur(18px); }

.ccb-psec:active {
  --vsec-angle: 160deg;
  --vsec-stop-a: var(--vmc-color-vault-700, #3B178A);
  --vsec-stop-b: var(--vmc-color-vault-900, #1a0a4a);
  transform: scale(0.97) translateY(1px);
  box-shadow:
    rgba(0, 0, 0, 0.28) 0px 2px 5px inset,
    rgba(0, 0, 0, 0.14) 0px 1px 3px;
}
.ccb-psec:active::after { opacity: 0; }

.ccb-psec:focus-visible {
  outline: 2px solid var(--vmc-color-vault-400, #AE8EFF);
  outline-offset: 3px;
}

.ccb-psec:disabled {
  background-image: none;
  background-color: var(--vmc-color-background-disabled, #E1E3E2);
  color: var(--vmc-color-neutral-700, #99A1AF);
  text-shadow: none;
  box-shadow: none;
  cursor: not-allowed;
  transform: none;
  border-color: transparent;
}
.ccb-psec:disabled::after { display: none; }

/* ══════════════════════════════════════════════════════════════════════════
   GHOST — .ccb-pghost
   Transparent con borde blanco semitransparente.
   Hover: relleno blanco → texto naranja
   ══════════════════════════════════════════════════════════════════════════ */
.ccb-pghost {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  height: 48px;
  padding: 0 28px;
  border-radius: 9999px;
  border: 2px solid rgba(255, 255, 255, 0.75);
  cursor: pointer;
  position: relative;
  overflow: hidden;

  font-family: var(--vmc-font-display, "Plus Jakarta Sans", sans-serif);
  font-size: 14px;
  font-weight: 600;
  color: var(--vmc-color-base-white, #fff);
  text-shadow: rgba(255, 255, 255, 0.15) 0px 1px 2px;
  background: transparent;

  box-shadow:
    rgba(255, 255, 255, 0.2) 0px 1px 0px 0px inset,
    rgba(255, 255, 255, 0.15) 0px 0px 12px 0px;

  transition:
    background 0.25s,
    border-color 0.25s,
    color 0.2s,
    transform 0.2s cubic-bezier(0.25, 0.8, 0.25, 1),
    box-shadow 0.25s;
}

.ccb-pghost::before {
  background: linear-gradient(rgba(255, 255, 255, 0.1) 0%, transparent 55%);
}

.ccb-pghost:hover {
  background: linear-gradient(135deg, #fff 0%, oklch(0.97 0.03 55) 100%);
  border-color: #fff;
  color: var(--vmc-color-orange-600, #ED8936);
  text-shadow: none;
  transform: translateY(-2px) scale(1.02);
  box-shadow:
    rgba(255, 255, 255, 0.5) 0px 1px 0px inset,
    rgba(0, 0, 0, 0.2) 0px 6px 20px;
}
.ccb-pghost:hover::after { opacity: 0.4; filter: blur(18px); }

.ccb-pghost:active {
  background: linear-gradient(135deg, var(--vmc-color-orange-700, #D46E20) 0%, oklch(0.52 0.18 45) 100%);
  border-color: var(--vmc-color-orange-700, #D46E20);
  color: var(--vmc-color-base-white, #fff);
  text-shadow: rgba(0, 0, 0, 0.25) 0px 1px 3px;
  transform: scale(0.97) translateY(1px);
  box-shadow: rgba(0, 0, 0, 0.22) 0px 2px 5px inset;
}
.ccb-pghost:active::after { opacity: 0; }

.ccb-pghost:focus-visible {
  outline: 2px solid rgba(255, 255, 255, 0.8);
  outline-offset: 3px;
}

.ccb-pghost:disabled {
  background: transparent;
  border-color: rgba(255, 255, 255, 0.3);
  color: rgba(255, 255, 255, 0.35);
  text-shadow: none;
  cursor: not-allowed;
  transform: none;
  box-shadow: none;
}
.ccb-pghost:disabled::after { display: none; }

/* ══════════════════════════════════════════════════════════════════════════
   SM GUEST — .ccb-pvbtn-sm
   Small pill con icon slot. Mismo gradiente naranja/purple pero 40px.
   ══════════════════════════════════════════════════════════════════════════ */
.ccb-pvbtn-sm {
  --vbtn-angle: 135deg;
  --vbtn-stop-a: var(--vmc-color-orange-600, #ED8936);
  --vbtn-stop-b: var(--vmc-color-vault-500, #8460E5);

  display: inline-flex;
  align-items: center;
  gap: 8px;
  height: 40px;
  padding: 0 16px 0 4px;
  border-radius: 9999px;
  border: 2px solid transparent;
  cursor: pointer;
  position: relative;
  overflow: hidden;

  font-family: var(--vmc-font-display, "Plus Jakarta Sans", sans-serif);
  font-size: 14px;
  font-weight: 600;
  color: var(--vmc-color-base-white, #fff);
  text-shadow: rgba(0, 0, 0, 0.2) 0px 1px 2px;

  background-image:
    linear-gradient(var(--vbtn-angle), var(--vbtn-stop-a) 0%, var(--vbtn-stop-a) 40%, var(--vbtn-stop-b) 100%),
    linear-gradient(135deg, #fff 0%, #fbc47d 25%, #ae8eff 75%, #fff 100%);
  background-origin: border-box;
  background-clip: padding-box, border-box;

  box-shadow:
    rgba(255, 255, 255, 0.25) 0px 1px 0px 0px inset,
    rgba(237, 137, 54, 0.25) 0px 2px 6px 0px;

  transition:
    --vbtn-angle 0.4s cubic-bezier(0.25, 0.8, 0.25, 1),
    --vbtn-stop-a 0.35s,
    --vbtn-stop-b 0.35s,
    transform 0.2s cubic-bezier(0.25, 0.8, 0.25, 1),
    box-shadow 0.25s;
}

.ccb-pvbtn-sm::before {
  background: linear-gradient(rgba(255, 255, 255, 0.15) 0%, transparent 55%);
}

.ccb-pvbtn-sm:hover {
  --vbtn-angle: 220deg;
  --vbtn-stop-a: var(--vmc-color-orange-400, #FBC47D);
  --vbtn-stop-b: var(--vmc-color-vault-400, #AE8EFF);
  transform: translateY(-1px) scale(1.02);
  box-shadow:
    rgba(255, 255, 255, 0.2) 0px 1px 0px inset,
    rgba(132, 96, 229, 0.3) 0px 6px 18px,
    rgba(237, 137, 54, 0.35) 0px 3px 8px;
}

.ccb-pvbtn-sm:active {
  --vbtn-angle: 135deg;
  --vbtn-stop-a: var(--vmc-color-orange-700, #D46E20);
  --vbtn-stop-b: var(--vmc-color-vault-600, #5A35C2);
  transform: scale(0.97) translateY(1px);
  box-shadow:
    rgba(0, 0, 0, 0.22) 0px 2px 4px inset,
    rgba(0, 0, 0, 0.1) 0px 1px 2px;
}

.ccb-pvbtn-sm:focus-visible {
  outline: 2px solid var(--vmc-color-vault-400, #AE8EFF);
  outline-offset: 3px;
}

/* ══════════════════════════════════════════════════════════════════════════
   SM LOGGED-IN — .ccb-pvbtn-auth
   Mismo sm pill pero fondo auth (orange/vault) con username bold
   ══════════════════════════════════════════════════════════════════════════ */
.ccb-pvbtn-auth {
  --vbtn-angle: 135deg;
  --vbtn-stop-a: var(--vmc-color-orange-600, #ED8936);
  --vbtn-stop-b: var(--vmc-color-vault-500, #8460E5);

  display: inline-flex;
  align-items: center;
  gap: 8px;
  height: 40px;
  padding: 0 16px 0 4px;
  border-radius: 9999px;
  border: 2px solid transparent;
  cursor: pointer;
  position: relative;
  overflow: hidden;

  font-family: var(--vmc-font-display, "Plus Jakarta Sans", sans-serif);
  font-size: 14px;
  font-weight: 600;
  color: var(--vmc-color-base-white, #fff);
  text-shadow: rgba(0, 0, 0, 0.22) 0px 1px 2px;

  background-image:
    linear-gradient(var(--vbtn-angle), var(--vbtn-stop-a) 0%, var(--vbtn-stop-a) 40%, var(--vbtn-stop-b) 100%),
    linear-gradient(135deg, #fff 0%, #fbc47d 25%, #ae8eff 75%, #fff 100%);
  background-origin: border-box;
  background-clip: padding-box, border-box;

  box-shadow:
    rgba(255, 255, 255, 0.28) 0px 1px 0px 0px inset,
    rgba(237, 137, 54, 0.3) 0px 2px 6px 0px;

  transition:
    --vbtn-angle 0.4s cubic-bezier(0.25, 0.8, 0.25, 1),
    --vbtn-stop-a 0.35s,
    --vbtn-stop-b 0.35s,
    transform 0.2s cubic-bezier(0.25, 0.8, 0.25, 1),
    box-shadow 0.25s;
}

.ccb-pvbtn-auth::before {
  background: linear-gradient(rgba(255, 255, 255, 0.17) 0%, transparent 55%);
}

.ccb-pvbtn-auth::after {
  background: linear-gradient(135deg, var(--vmc-color-orange-600, #ED8936), var(--vmc-color-vault-500, #8460E5));
}

.ccb-pvbtn-auth:hover {
  --vbtn-angle: 220deg;
  --vbtn-stop-a: var(--vmc-color-orange-400, #FBC47D);
  --vbtn-stop-b: var(--vmc-color-vault-400, #AE8EFF);
  transform: translateY(-2px) scale(1.02);
  box-shadow:
    rgba(255, 255, 255, 0.22) 0px 1px 0px inset,
    rgba(132, 96, 229, 0.35) 0px 8px 24px,
    rgba(237, 137, 54, 0.4) 0px 4px 10px;
}
.ccb-pvbtn-auth:hover::after { opacity: 0.45; filter: blur(18px); }

.ccb-pvbtn-auth:active {
  --vbtn-angle: 135deg;
  --vbtn-stop-a: var(--vmc-color-orange-700, #D46E20);
  --vbtn-stop-b: var(--vmc-color-vault-600, #5A35C2);
  transform: scale(0.97) translateY(1px);
  box-shadow:
    rgba(0, 0, 0, 0.22) 0px 2px 5px inset,
    rgba(0, 0, 0, 0.12) 0px 1px 3px;
}
.ccb-pvbtn-auth:active::after { opacity: 0; }

.ccb-pvbtn-auth:focus-visible {
  outline: transparent solid 3px;
  outline-offset: 4px;
  transform: scale(0.98);
  box-shadow:
    0 0 0 2px var(--vmc-color-base-white, #fff),
    0 0 0 5px var(--vmc-color-vault-500, #8460E5),
    0 8px 16px -4px rgba(132, 96, 229, 0.3);
}
.ccb-pvbtn-auth:focus-visible::after { opacity: 0.2; }

/* ── Icon slots ─────────────────────────────────────────────────────────── */
.ccb-icon-slot-guest {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  background: rgba(255, 255, 255, 0.2);
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  position: relative;
  z-index: 2;
}

.ccb-icon-slot-auth {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  background: rgba(0, 0, 0, 0.18);
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  position: relative;
  z-index: 2;
}

.ccb-username {
  font-weight: 700;
  opacity: 0.92;
}

/* ── Reduced motion ──────────────────────────────────────────────────────── */
@media (prefers-reduced-motion: reduce) {
  .ccb-pvbtn,
  .ccb-psec,
  .ccb-pghost,
  .ccb-pvbtn-sm,
  .ccb-pvbtn-auth,
  .ccb-pvbtn::after,
  .ccb-psec::after,
  .ccb-pvbtn-sm::after,
  .ccb-pvbtn-auth::after {
    transition: none;
  }
}
`;

// ---------------------------------------------------------------------------
// CLASS RESOLVER
// ---------------------------------------------------------------------------

function resolveClass(
  size: ButtonSize,
  variant: ButtonVariant,
  authState: ButtonAuthState
): string {
  if (size === "sm") {
    if (authState === "logged-in") {
      return "ccb-pvbtn-auth";
    }
    return "ccb-pvbtn-sm";
  }
  if (variant === "secondary") {
    return "ccb-psec";
  }
  if (variant === "ghost") {
    return "ccb-pghost";
  }
  return "ccb-pvbtn";
}

// ---------------------------------------------------------------------------
// ICON SLOT
// ---------------------------------------------------------------------------

function IconSlot({
  icon,
  authState,
}: {
  icon: ReactNode;
  authState: ButtonAuthState;
}): JSX.Element {
  const slotClass =
    authState === "logged-in" ? "ccb-icon-slot-auth" : "ccb-icon-slot-guest";
  return <span className={slotClass}>{icon}</span>;
}

// ---------------------------------------------------------------------------
// COMPONENT
// ---------------------------------------------------------------------------

let stylesInjected = false;

export default function Button({
  variant = "primary",
  size = "md",
  icon,
  authState = "guest",
  children,
  disabled = false,
  onClick,
  type = "button",
  "aria-label": ariaLabel,
}: ButtonProps): JSX.Element {
  const btnClass = resolveClass(size, variant, authState);
  const hasIcon = size === "sm" && icon !== undefined;

  // Inject styles once per page (avoids duplicate <style> on multiple instances)
  if (typeof document !== "undefined" && !stylesInjected) {
    const existing = document.getElementById("concorde-button-styles");
    if (!existing) {
      const styleEl = document.createElement("style");
      styleEl.id = "concorde-button-styles";
      styleEl.textContent = BUTTON_STYLES;
      document.head.appendChild(styleEl);
    }
    stylesInjected = true;
  }

  return (
    <>
      {/* SSR: inject via <style> tag on first render */}
      <style
        id="concorde-button-styles-ssr"
        suppressHydrationWarning
        dangerouslySetInnerHTML={{ __html: BUTTON_STYLES }}
      />
      <button
        className={btnClass}
        disabled={disabled}
        onClick={onClick}
        type={type}
        aria-label={ariaLabel}
      >
        {hasIcon && <IconSlot icon={icon} authState={authState} />}
        {size === "sm" && authState === "logged-in"
          ? <span className="ccb-username">{children}</span>
          : children}
      </button>
    </>
  );
}
